version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-py27
      - test-py34
      - test-py35
      - test-py36
      - test-py37
      - test-py38
jobs:
  base_test: &base-test
    working_directory: ~/vertica_python_ci
    docker:
      # The first image listed becomes the job’s primary container. All
      # commands for a job execute in this container.  Susequent images can be
      # used to host services such as databases or webservers
      #
      # NOTE: the image here is a placeholder, overridden by all actually-used jobs.
      - image: circleci/python:2.7
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "./.circleci/requires.txt" }}

      - run:
          name: "Create venv and install dependencies"
          command: |
            python -m ${VENV_MODULE:-venv} _venv
            source ./_venv/bin/activate
            pip install -r ./.circleci/requires.txt

      - save_cache:
          paths:
            - ./_venv
          key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "./.circleci/requires.txt" }}

      - run:
          name: "Run unit tests"
          command: |
            source ./_venv/bin/activate
            mkdir -p ./_test_results/unit_tests/
            python -m pytest \
              vertica_python/tests \
              . -m unit_test \
              --junitxml ./_test_results/unit_tests/results.xml

      - store_test_results:
          path: ./_test_results


  test-py27:
    <<: *base-test
    docker:
      - image: circleci/python:2.7
        environment:
          VENV_MODULE: virtualenv
  test-py34:
    <<: *base-test
    docker:
      - image: circleci/python:3.4
  test-py35:
    <<: *base-test
    docker:
      - image: circleci/python:3.5
  test-py36:
    <<: *base-test
    docker:
      - image: circleci/python:3.6
  test-py37:
    <<: *base-test
    docker:
      - image: circleci/python:3.7
  test-py38:
    <<: *base-test
    docker:
      - image: circleci/python:3.8
